---
# AI Website Project Inventory
# This file defines the hosts and groups for deployment

all:
  children:
    production:
      hosts:
        web-server-1:
          ansible_host: # Replace with your production server IP
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/production_key
        
        web-server-2:
          ansible_host: # Replace with your backup server IP  
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/production_key
          
    staging:
      hosts:
        staging-server:
          ansible_host: # Replace with your staging server IP
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/staging_key
          
    development:
      hosts:
        dev-server:
          ansible_host: # Replace with your dev server IP
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/dev_key
        
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"

  vars:
    # Global variables
    project_name: ai-website-project
    app_user: www-data
    app_group: www-data
    nginx_user: www-data
    node_version: "18.x"
    
    # Application paths
    app_directory: /var/www/{{ project_name }}
    nginx_sites_available: /etc/nginx/sites-available
    nginx_sites_enabled: /etc/nginx/sites-enabled
    
    # SSL Configuration
    ssl_cert_path: /etc/ssl/certs
    ssl_key_path: /etc/ssl/private
    
    # Database (if needed)
    db_name: "{{ project_name }}"
    db_user: "{{ project_name }}_user"